"""Tests for QueryService.

Uses real in-memory DuckDB + mocked LLM provider.
"""

from unittest.mock import AsyncMock, MagicMock

import pytest

from dry_data.exceptions import LLMError, QueryError
from dry_data.models.api import PlotlySpec, QueryResponse
from dry_data.services.query_service import QueryService
from dry_data.warehouse.repository_base import BaseDataRepository


@pytest.fixture
def repo(sample_dim_year):
    return BaseDataRepository(sample_dim_year)


@pytest.fixture
def mock_llm():
    llm = MagicMock()
    llm.generate_sql = AsyncMock(return_value="SELECT year FROM dim_year LIMIT 1")
    llm.narrate_results = AsyncMock(return_value="The earliest year is 2020.")
    llm.suggest_chart = AsyncMock(return_value=None)
    return llm


# CATCHES: answer_question returns raw QueryResult instead of QueryResponse
@pytest.mark.asyncio
async def test_answer_question_returns_query_response(repo, mock_llm):
    service = QueryService(data_repo=repo, llm_provider=mock_llm)
    response = await service.answer_question("What years are available?")
    assert isinstance(response, QueryResponse)


# CATCHES: answer_question swallows the SQL generated by the LLM instead of
#          including it in the response for transparency
@pytest.mark.asyncio
async def test_answer_question_includes_sql_in_response(repo, mock_llm):
    service = QueryService(data_repo=repo, llm_provider=mock_llm)
    response = await service.answer_question("What years?")
    assert "dim_year" in response.sql


# CATCHES: answer_question raises QueryError instead of surfacing it as
#          error field in QueryResponse
@pytest.mark.asyncio
async def test_answer_question_propagates_query_error(repo, mock_llm):
    mock_llm.generate_sql = AsyncMock(return_value="DROP TABLE dim_year")
    service = QueryService(data_repo=repo, llm_provider=mock_llm)
    with pytest.raises(QueryError):
        await service.answer_question("Drop it")


# CATCHES: LLMError from narrate_results is swallowed and response returns
#          empty narrative instead of raising
@pytest.mark.asyncio
async def test_answer_question_propagates_llm_error(repo, mock_llm):
    mock_llm.narrate_results = AsyncMock(side_effect=LLMError("model down"))
    service = QueryService(data_repo=repo, llm_provider=mock_llm)
    with pytest.raises(LLMError):
        await service.answer_question("What years?")


# CATCHES: suggest_chart result is ignored instead of included in QueryResponse
@pytest.mark.asyncio
async def test_answer_question_includes_chart_when_suggested(repo, mock_llm):
    chart_spec = PlotlySpec(data=[{"type": "bar", "x": [2020], "y": [1]}])
    mock_llm.suggest_chart = AsyncMock(return_value=chart_spec)
    service = QueryService(data_repo=repo, llm_provider=mock_llm)
    response = await service.answer_question("Show a chart of years")
    assert isinstance(response.chart, PlotlySpec)
    assert response.chart.data == chart_spec.data
